[mesh]
source = "möbius.ply"

[camera]
fov = 45.0
eye = [-4.7, -8.0, 35.0]
look_at = [11.0, 13.0, 6.0]

[style]
vertex_size = 0
vertex_stroke_width = 0
edge_width = 1

[light]
enabled = true

[render]
backface_culling = false
